// <auto-generated />
namespace Awesome.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Book_And_Excerpt_Request : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book_And_Excerpt_Request));
        
        string IMigrationMetadata.Id
        {
            get { return "201605221955024_Book_And_Excerpt_Request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
