// <auto-generated />
namespace Awesome.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customer_Request_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_Request_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201605251926303_Customer_Request_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
